import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import TopNavbar from "./components/navbar/TopNavbar";
import Footer from "./components/footer/Footer";
import StoreProvider from "./StoreProvider";
import { SessionProvider } from "next-auth/react";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "e-com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
      <html lang="en">
        <body className={outfit.className}>
          <StoreProvider>
            <TopNavbar />
            <Navbar />
            {children}
            <Footer />
          </StoreProvider>
        </body>
      </html>
    </SessionProvider>
  );
}
